esphome:
  name: espcam1

esp32:
  board: esp32cam
  framework:
    type: arduino

logger:

api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: ""
  password: ""
  use_address: 

i2c:
  - id: camera_i2c
    sda: GPIO26
    scl: GPIO27

esp32_camera:
  name: "Garage Camera"
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_id: camera_i2c
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  max_framerate: 15 fps
  idle_framerate: 0.05 fps
  resolution: 1024x768
  jpeg_quality: 35

output:
  - platform: gpio
    pin: GPIO4
    id: camera_flash_led

light:
  - platform: binary
    name: "Garage Camera Flash"
    output: camera_flash_led
